const PRODUCT_DISPLAY_NAMES = {
  "Product_001": "Amul Full Cream Milk",
  "Product_002": "Lays Classic Chips",
  "Product_003": "Mother Dairy Frozen Peas",
  "Product_004": "Fresh Chicken Breast",
  "Product_006": "Fresh Spinach Bundle",
  "Product_007": "Tide Detergent Powder",
  "Product_008": "McCain French Fries",
  "Product_009": "Fresh Apple (Red Delicious)",
  "Product_010": "ITC Master Chef Frozen Paratha",
  "Product_011": "Fresh Cauliflower",
  "Product_012": "Fresh Banana (Robusta)",
  "Product_013": "Fortune Basmati Rice (1kg)",
  "Product_015": "Modern Bread (Whole Wheat)",
  "Product_016": "Tata Sampann Toor Dal",
  "Product_017": "Fresh Tomato",
  "Product_018": "Coca-Cola (2L)",
  "Product_019": "Harvest Gold Brown Bread",
  "Product_020": "Amul Butter (500g)",
  "Product_021": "Britannia Croissant",
  "Product_022": "Pepsi (2L)",
  "Product_023": "Britannia Whole Wheat Bread",
  "Product_024": "Surf Excel Liquid Detergent",
  "Product_025": "Fresh Potato",
  "Product_027": "Fresh Orange (Nagpur)",
  "Product_028": "Fresh Mutton Curry Cut",
  "Product_029": "Bingo! Chips (Tangy Tomato)",
  "Product_030": "Mr. Muscle Glass Cleaner",
  "Product_031": "Fresh Onion",
  "Product_032": "Amul Cheese Slices",
  "Product_033": "Harpic Toilet Cleaner",
  "Product_034": "Fresh Brinjal",
  "Product_035": "Fresh Pomegranate",
  "Product_036": "Amul Ice Cream (Vanilla)",
  "Product_037": "Vim Dishwashing Bar",
  "Product_038": "Fresh Cucumber",
  "Product_039": "Fresh Mango (Alphonso)",
  "Product_041": "Fresh Fish (Rohu)",
  "Product_042": "Dettol Hand Sanitizer",
  "Product_043": "Kwality Walls Frozen Dessert",
  "Product_044": "Lizol Floor Cleaner",
  "Product_045": "Fresh Carrot",
  "Product_046": "Fresh Beans (French)",
  "Product_047": "Britannia Cake (Vanilla)",
  "Product_048": "Fresh Pumpkin",
  "Product_049": "Fresh Grapes (Green)",
  "Product_051": "Amul Curd (Fresh)",
  "Product_052": "Haldiram's Namkeen (Aloo Bhujia)",
  "Product_053": "Tata Tea (Premium)",
  "Product_054": "Pillsbury Atta (5kg)",
  "Product_055": "Fresh Papaya",
  "Product_057": "Fresh Cabbage",
  "Product_060": "Amul Buttermilk (Chaas)",
  "Product_061": "Fresh Mushroom",
  "Product_062": "Britannia Milk Bikis",
  "Product_063": "Kurkure Masala Munch",
  "Product_064": "Fresh Ginger",
  "Product_065": "MTR Ready-to-Eat Sambhar",
  "Product_066": "Fresh Garlic",
  "Product_067": "Patanjali Ghee (1L)",
  "Product_068": "Fresh Lemon",
  "Product_069": "Maggie Noodles (12 Pack)",
  "Product_070": "Fresh Sweet Potato",
  "Product_073": "Fortune Mustard Oil (1L)",
  "Product_074": "Fresh Ridge Gourd",
  "Product_075": "Dabur Honey (500g)",
  "Product_076": "Fresh Bitter Gourd",
  "Product_077": "Kellogg's Corn Flakes",
  "Product_078": "Fresh Bottle Gourd",
  "Product_079": "Saffola Gold Oil (1L)",
  "Product_080": "Fresh Radish (White)",
  "Product_081": "Tata Salt (1kg)",
  "Product_082": "Fresh Beetroot",
  "Product_083": "Fortune Refined Oil (1L)",
  "Product_084": "Fresh Ladyfinger (Bhindi)",
  "Product_085": "Fresh Pineapple",
  "Product_087": "Parle-G Biscuits (100g)",
  "Product_088": "Fresh Capsicum (Green)",
  "Product_089": "Good Day Cashew Biscuits",
  "Product_090": "Fresh Coriander Leaves",
  "Product_091": "Fresh Coconut",
  "Product_093": "Aashirvaad Shakti Bhog Atta (10kg)",
  "Product_094": "Moong Dal (Split, 1kg)",
  "Product_096": "Chana Dal (1kg)",
  "Product_098": "Masoor Dal (Red, 1kg)",
  "Product_099": "Fortune Besan (1kg)",
  "Product_100": "Fresh Curry Leaves",
  "Product_102": "Fresh Drumstick (Moringa)",
  "Product_103": "Madhur Pure Sugar (1kg)",
  "Product_104": "Taj Mahal Tea (Premium)",
  "Product_105": "Red Label Tea (500g)",
  "Product_106": "Nescafe Classic Coffee",
  "Product_107": "Bournvita (500g)",
  "Product_108": "Horlicks (500g)",
  "Product_109": "Complan (500g)",
  "Product_110": "Kissan Mixed Fruit Jam",
  "Product_111": "Amul Masti Buttermilk",
  "Product_112": "Mother Dairy Paneer (200g)",
  "Product_113": "Amul Shrikhand (Kesar)",
  "Product_114": "Amul Lassi (Mango)",
  "Product_115": "Britannia Cheese Slices",
  "Product_116": "Gowardhan Paneer (Fresh)",
  "Product_117": "Amul Gold Milk (1L)",
  "Product_119": "Milky Mist Paneer (Fresh)",
  "Product_120": "Fresh Watermelon",
  "Product_122": "Fresh Mosambi (Sweet Lime)",
  "Product_123": "Fresh Guava",
  "Product_124": "Fresh Pear",
  "Product_125": "Fresh Plum",
  "Product_127": "Fresh Sapota (Chikoo)",
  "Product_128": "Fresh Custard Apple",
  "Product_129": "Fresh Jackfruit",
  "Product_130": "Fresh Muskmelon",
  "Product_131": "Britannia Rusk (Cardamom)",
  "Product_132": "Parle Monaco Biscuits",
  "Product_133": "Sunfeast Dark Fantasy",
  "Product_134": "Haldiram's Bhujia Sev",
  "Product_135": "Pringles Sour Cream",
  "Product_136": "Tata Gluco Plus Energy Drink",
  "Product_137": "Bourbon Biscuits",
  "Product_138": "Munch Chocolate Wafer",
  "Product_139": "KitKat Chocolate (4 Fingers)",
  "Product_140": "Dairy Milk Silk Chocolate",
  "Product_141": "5 Star Chocolate",
  "Product_142": "Gems Chocolate (Small Pack)",
  "Product_143": "Haldiram's Papad (Moong)",
  "Product_144": "MTR Idli/Dosa Batter (1kg)",
  "Product_145": "Patanjali Aata Noodles",
  "Product_148": "Kissan Tomato Ketchup",
  "Product_149": "Everest Kitchen King Masala",
  "Product_150": "MDH Chana Masala",
  "Product_151": "Maggi Hot & Sweet Sauce",
  "Product_152": "Fortune Suji (Rava, 500g)",
  "Product_153": "Aashirvaad Maida (1kg)",
  "Product_154": "Tata Sampann Rajma (500g)",
  "Product_155": "Fortune Chole Masala",
  "Product_156": "Daawat Basmati Rice (1kg)",
  "Product_157": "India Gate Basmati Rice (1kg)",
  "Product_159": "Kohinoor Basmati Rice (1kg)",
  "Product_160": "Fresh Curry Leaves",
  "Product_162": "Bajaj Almond Oil Drops",
  "Product_163": "Dabur Chyawanprash (500g)",
  "Product_164": "Patanjali Amla Juice (1L)",
  "Product_165": "Dabur Pudin Hara",
  "Product_166": "Vicks Vaporub (Small)",
  "Product_167": "Moov Pain Relief Spray",
  "Product_168": "Dettol Antiseptic (100ml)",
  "Product_169": "Band-Aid Fabric Strips",
  "Product_170": "Cinthol Soap (Lime)",
  "Product_171": "Lux Soap (Rose)",
  "Product_172": "Dove Soap (Cream Beauty)",
  "Product_173": "Pears Soap (Pure & Gentle)",
  "Product_174": "Lifebuoy Soap (Total)",
  "Product_175": "Sunsilk Shampoo (Black)",
  "Product_176": "Clinic Plus Shampoo (200ml)",
  "Product_177": "Pantene Shampoo (Daily Care)",
  "Product_178": "Head & Shoulders Shampoo",
  "Product_179": "Dove Shampoo (Intensive Repair)",
  "Product_180": "Colgate Dental Cream (100g)",
  "Product_182": "Patanjali Dant Kanti",
  "Product_184": "Closeup Toothpaste (Red Hot)",
  "Product_186": "Sensodyne Repair Toothpaste",
  "Product_187": "Odomos Mosquito Repellent",
  "Product_188": "Good Knight Machine + Refill",
  "Product_189": "All Out Mosquito Repellent",
  "Product_190": "Hit Insect Spray (Neem)",
  "Product_192": "Tata Salt Iodized (1kg)",
  "Product_193": "Catch Black Pepper Powder",
  "Product_194": "Everest Red Chilli Powder",
  "Product_195": "MDH Turmeric Powder (Haldi)",
  "Product_196": "MDH Coriander Powder (Dhaniya)",
  "Product_197": "Everest Garam Masala",
  "Product_198": "Patanjali Cumin Seeds (Jeera)",
  "Product_199": "Tata Sampann Mustard Seeds",
  "Product_200": "Catch Chaat Masala",
};

function displayName(product) {
  if (!product) return 'Unknown';
  const name = typeof product === 'string' ? product : (product.product_name || product.name || '');
  return PRODUCT_DISPLAY_NAMES[name] || name;
}
